### ISSUE TITLE
View multiple demo projects to take inspiration from

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/documentation#115]

**Comment by rihp** [comment]
List of some highlight wrappers which we can leverage for a simple demo

- Tezos by blockwatch
- Gelato network
- Near 
- Uniswap V3 ()

**Comment by dOrgJelli** [comment]
Demo projects can be seen by looking at both the "demos" and "integrations" repos here:
https://github.com/polywrap/demos
https://github.com/polywrap/integrations

**Comment by dOrgJelli** [comment]
Requesting review: @evanjacobs @rihp

**Comment by evanjacobs** [comment]
I think the motivation for this task was to survey other projects to see if there was anything we could apply to our own demos. That's pretty subjective so it's hard to tell if this task is complete. However, for Alpha, I think we're aiming more for the existence of demos rather than judging the quality of them. Once we have analytics in place, we should be able to get a better sense for whether people are looking at the demos and finding them useful. Until then, I'm ok with calling this task complete.
