### ISSUE TITLE
I want to know that everything has been fully tested before it was released

### ISSUE THREAD

**Issue by evanjacobs** [polywrap/documentation#135]
There needs to be a list of test cases that need to be executed manually for each release and also periodically. Each issue should add test cases to this list before it can be marked as "done".

- [ ] polywrap/integrations#66
- [x] polywrap/demos#53

**Comment by evanjacobs** [comment]
Potential tools for test case management:
https://qase.io/

**Comment by dOrgJelli** [comment]
In terms of "end user QA", I just want to highlight here that we have **basic** e2e testing for the CLI located here: https://github.com/polywrap/monorepo/tree/prealpha/packages/cli/src/__tests__/e2e

Additionally I feel we need more extensive CLI integration testing for our demo & integration projects located here:
https://github.com/polywrap/demos
https://github.com/polywrap/integrations

New release of a tool-chain should have a clear (and automated) sets of breaking changes that occur in example user projects.

**Comment by Niraj-Kamdar** [comment]
@dOrgJelli  I can help with this and also setup the CI/CD pipeline for this if not already in progress.

**Comment by dOrgJelli** [comment]
I think having your expertise put to use here on Polywrap's CI/CD pipeline would be amazing @Niraj-Kamdar. I have a few thoughts on how we could tackle this, and would like to have a call with you to discuss further and get some thoughts out of my head (and get your own as well :slightly_smiling_face:). I'll schedule a call with you now.

**Comment by evanjacobs** [comment]
There are opportunities to improve CI in several repos. Need to determine what the bar is for Alpha.

**Comment by Niraj-Kamdar** [comment]
Here are notes from the brainstorming session that I had with @dOrgJelli: https://hackmd.io/@zgxjyig-QeyCd_p_Oc0yBQ/ByK0Yiivq

**Comment by Niraj-Kamdar** [comment]
# Action items for alpha

## Integrations
- create CI/CD pipeline for integration plugins (must)
- create CI/CD pipeline for integration wrappers (must)
- migrate tezos and near integrations out of the repo and let the respective team manage those (nice to have)
  - by doing so we won't need to manage integrations created by third parties by ourselves
  - it will also reduce overhead for the respective team working on integration since they can move at their own pace
  
## Docs
- don't automatically sync code snippets in docs to avoid the issue of docs content being out of sync with the code
- explicitly mention the version for which docs have been written to avoid confusion for the users (can also have multiple versions of docs lying around just like many large projects have (Ex: Python, Vue, etc))
- have a process to update the toolchain version to the latest automatically but can only be initiated by the tech writer and it will be the job of the tech writer to assure the quality of the docs after the update
- have live demos mentioned in docs

## Demos
- create ci/cd pipelines for demos
- move client-thread and datetime packages into integrations
- demos should share common `demos.web3api.eth` domain
  - simple-storage: `simple-storage.demos.web3api.eth`
  - hello-world: `hello-world.demos.web3api.eth` 
- make a PR or create an issue whenever new toolchain version releases (post-alpha)

**Comment by krisbitney** [comment]
Demos CI added by @Niraj-Kamdar. See https://github.com/polywrap/demos/pull/77 and https://github.com/polywrap/demos/pull/80. Amazing work!

**Comment by krisbitney** [comment]
Integrations CI also added by @Niraj-Kamdar. See https://github.com/polywrap/integrations/issues/66. MVP!

**Comment by krisbitney** [comment]
@Niraj-Kamdar Are we ready to close this?

**Comment by Niraj-Kamdar** [comment]
Since this is a story we still need to wait until we complete the integrations CI/CD, I still need to add system integrations for CI

**Comment by dOrgJelli** [comment]
Closing this story, and tracking the remaining work in this issue: https://github.com/polywrap/integrations/issues/66
