### ISSUE TITLE
what should the map type be mapped to in both client and wasm?

### ISSUE THREAD

**Issue by Niraj-Kamdar** [polywrap/documentation#213]
https://docs.polywrap.io/quick-start/wrapper-schema  why do we have rust Map as BTree? 
shouldn't it be HashMap because that's what it is in the client and btree is something that we use very rarely where we need to maintain key order? (open to discussion though since in c++ it's map and unordered_map but map means hash map in js )

**Comment by dOrgJelli** [comment]
PR is here: https://github.com/polywrap/toolchain/pull/1201

Will update documentation now.

**Comment by dOrgJelli** [comment]
Okay so it looks like for serialization purposes `BTreeMap` is indeed desired. This is for 2 reasons:
- It provides a predictable ordering of key/value pairs, so that serialization is not random by consistent. I tried changing the `wasm/rs` runtime to use `HashMap`, and I cannot get the MsgPack tests to pass because each time they run the ordering of key/value pairs is different. [Source](https://news.ycombinator.com/item?id=27700662)
- `BTreeMap` is actually quite a bit faster, and is used in the `serde-json` library for this (and the above) reason. [Source](https://users.rust-lang.org/t/hashmap-vs-btreemap/13804)

So it seems to me we actually want to keep using `BTreeMap` :)
